-- SQLite schema for robotcontrolserver
-- Generated from DbObject classes

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS MAP (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    MINIOURL TEXT,
    CREATEAT DATETIME
);

CREATE TABLE IF NOT EXISTS POINTTYPE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    DESCRIPTION TEXT,
    CREATEAT DATETIME
);

CREATE TABLE IF NOT EXISTS POINT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MAPID INTEGER NOT NULL,
    NAME TEXT,
    X REAL,
    Y REAL,
    POINTTYPEID INTEGER,
    CREATEAT DATETIME,
    FOREIGN KEY (MAPID) REFERENCES MAP(ID) ON DELETE CASCADE,
    FOREIGN KEY (POINTTYPEID) REFERENCES POINTTYPE(ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IX_POINT_MAPID ON POINT(MAPID);
CREATE INDEX IF NOT EXISTS IX_POINT_POINTTYPEID ON POINT(POINTTYPEID);

CREATE TABLE IF NOT EXISTS ROUTE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MAPID INTEGER NOT NULL,
    NAME TEXT,
    DESCRIPTION TEXT,
    FROMPOINTID INTEGER,
    TOPOINTID INTEGER,
    CREATEAT DATETIME,
    FOREIGN KEY (MAPID) REFERENCES MAP(ID) ON DELETE CASCADE,
    FOREIGN KEY (FROMPOINTID) REFERENCES POINT(ID) ON DELETE SET NULL,
    FOREIGN KEY (TOPOINTID) REFERENCES POINT(ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IX_ROUTE_MAPID ON ROUTE(MAPID);
CREATE INDEX IF NOT EXISTS IX_ROUTE_FROMPOINTID ON ROUTE(FROMPOINTID);
CREATE INDEX IF NOT EXISTS IX_ROUTE_TOPOINTID ON ROUTE(TOPOINTID);

CREATE TABLE IF NOT EXISTS ROBOTTYPE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MODELNAME TEXT,
    MAXCAPACITY INTEGER NOT NULL DEFAULT 1,
    CREATEAT DATETIME
);

CREATE TABLE IF NOT EXISTS ROBOT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    INTERFACENAME TEXT,
    MANUFACTURER TEXT,
    SERIALNUMBER TEXT UNIQUE,
    ROBOTTYPEID INTEGER,
    CREATEAT DATETIME,
    FOREIGN KEY (ROBOTTYPEID) REFERENCES ROBOTTYPE(ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IX_ROBOT_ROBOTTYPEID ON ROBOT(ROBOTTYPEID);

CREATE TABLE IF NOT EXISTS ROBOTTASK (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    DESCRIPTION TEXT,
    ROBOTTYPEID INTEGER,
    DELIVERYFROMPOINTID INTEGER,
    DELIVERYTOPOINTID INTEGER,
    CAPACITY INTEGER,
    CREATEAT DATETIME,
    FOREIGN KEY (ROBOTTYPEID) REFERENCES ROBOTTYPE(ID) ON DELETE SET NULL,
    FOREIGN KEY (DELIVERYFROMPOINTID) REFERENCES POINT(ID) ON DELETE SET NULL,
    FOREIGN KEY (DELIVERYTOPOINTID) REFERENCES POINT(ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IX_ROBOTTASK_ROBOTTYPEID ON ROBOTTASK(ROBOTTYPEID);
CREATE INDEX IF NOT EXISTS IX_ROBOTTASK_FROMPOINTID ON ROBOTTASK(DELIVERYFROMPOINTID);
CREATE INDEX IF NOT EXISTS IX_ROBOTTASK_TOPOINTID ON ROBOTTASK(DELIVERYTOPOINTID);

CREATE TABLE IF NOT EXISTS ROBOTTASKTEMPLATE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MAPID INTEGER NOT NULL,
    FROMPOINTID INTEGER NOT NULL,
    TOPOINTID INTEGER NOT NULL,
    ROBOTTYPEID INTEGER NOT NULL,
    NAME TEXT,
    DESCRIPTION TEXT,
    CREATEAT DATETIME,
    FOREIGN KEY (MAPID) REFERENCES MAP(ID) ON DELETE CASCADE,
    FOREIGN KEY (FROMPOINTID) REFERENCES POINT(ID) ON DELETE CASCADE,
    FOREIGN KEY (TOPOINTID) REFERENCES POINT(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROBOTTYPEID) REFERENCES ROBOTTYPE(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_ROBOTTASKTEMPLATE_MAPID ON ROBOTTASKTEMPLATE(MAPID);
CREATE INDEX IF NOT EXISTS IX_ROBOTTASKTEMPLATE_FROMPOINTID ON ROBOTTASKTEMPLATE(FROMPOINTID);
CREATE INDEX IF NOT EXISTS IX_ROBOTTASKTEMPLATE_TOPOINTID ON ROBOTTASKTEMPLATE(TOPOINTID);
CREATE INDEX IF NOT EXISTS IX_ROBOTTASKTEMPLATE_ROBOTTYPEID ON ROBOTTASKTEMPLATE(ROBOTTYPEID);
